name= input("enter your name")
branch= input("Tell me your branch")
gender=input("What is your Gender")
collegeName=input("What is your college name")
Age =int(input("Enter your age"))
print("Name: ",name)
print("Branch: ",branch)
print("Gender: ",gender)
print("College Name: ",collegeName)
print("Age: ",Age)
